### ISSUE TITLE
Problems with nonsolid players

### ISSUE THREAD

**Issue by Tucumanos** [wootguy/bspguy#1]
![unknown](https://user-images.githubusercontent.com/34820641/81614832-03c8a200-93b7-11ea-92e2-c52211fb94c9.png)
Players falls into a infinite loop when they change state to nonsolid using:
{
"origin" "-2376 3400 -692"
"m_iszValueName" "solid"
"m_iszNewValue" "0"
"target" "!activator"
"targetname" "game_playerspawn"
"classname" "trigger_changevalue"
"$s_bspguy_map_source" "rl00u"
}
I merge a few maps from residual life.
Also some angles and brushes are kinda messed up, see image.

**Comment by wootguy** [comment]
what command did you use? I'm seeing broken faces and collision on the tram but not the angles are fine.

**Comment by Tucumanos** [comment]
I use
bspguy merge test.bsp -maps "rl00r.bsp, rl00t.bsp, rl00u.bsp, rl00s.bsp"

**Comment by wootguy** [comment]
Angles were still fine for me, so I think maybe some plugin or entity setting is causing that. The brushes should be fixed in this version:
[bspguy_v2_wip.zip](https://github.com/wootguy/bspguy/files/4612825/bspguy_v2_wip.zip)

I noticed there's a clipnode overflow when using that command. When the clipnodes overflow then collision will be broken for random stuff in the map. The tool really shouldn't even save the output file when that happens. You'll need to try some of [this stuff in the wiki](https://github.com/wootguy/bspguy/wiki/Merging-workflow#clipnodes-reduction) if you want to merge those maps.

**Comment by Tucumanos** [comment]
Ok, I'll look into, thanks!.
