### ISSUE TITLE
fgd parsing order incorrect

### ISSUE THREAD

**Issue by Bluespark99** [wootguy/bspguy#101]
Where a spawnflag is common to both baseclass and entity the baseclass values are used in preference to the entity values leading to the wrong spawnflag descriptions in keyvalue editor / flags tab.

Best example is trigger_push where spawnflags (dec value) 1,2,8 & 16 differ between baseclass Trigger and entity trigger_push. Where there is conflict baseclass values are displayed in keyvalue / flags tab.

**Comment by UnrealKaraulov** [comment]
@wootguy 

I think this https://github.com/UnrealKaraulov/newbspguy/commit/c42f15f5951a30d03b22954488bb6d8c401951cf
 can fix this issue, but this is as patch, because I don't know problem origin. 
But it works, I think :)

@Bluespark99 you can test this issue with my fork of this project, https://github.com/UnrealKaraulov/newbspguy/releases ?
