### ISSUE TITLE
change class button in properties window does nothing

### ISSUE THREAD

**Issue by Underqualified-Gunman** [wootguy/bspguy#16]
when in the properties window and attempting to change the class of an object nothing occurs

**Comment by wootguy** [comment]
I think you need to add the FGD path in settings. I'm guessing every point entity looks like a purple cube, too.

![image](https://user-images.githubusercontent.com/12087544/102820447-1f068180-438a-11eb-94b6-03632d413e18.png)

I think someone else had a problem where the FGD wasn't working, but a restart fixed it or something.

**Comment by ghostboy1225** [comment]
yeah all entities look like different cubes.  figured it would have been fine since i was loading the stock HL1 FGDs sorry for late reply been doing christmas prep. assumed that stock HL1 ffgd would be better cause of how i'm using BSPguy (makinga chapter select mod and need to plop in relevant changelevel data for the chapter select select level)

**Comment by ghostboy1225** [comment]
think my issue is due to loading half-life.fgd not sven coop.fgdi know the program doesn't play well if the base directory isn't commom/svencoop

**Comment by wootguy** [comment]
Adding the half-life fgd works for me, but I got the same bug when trying to load that _and_ an invalid fgd.

![image](https://user-images.githubusercontent.com/12087544/103162695-91bb9680-47a8-11eb-9916-b3dd034bb72e.png)
^ that broken path to `sven-coop.fgd` is added by default. The class change menu was broken until I removed or fixed that path.

**Comment by wootguy** [comment]
fixed in 2fc27c4
